services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - c://Users//erison//Desktop//django//LOTRMarket://var//lib//postgresql//data 
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "gandalf_the_white@ainur.com"
      PGADMIN_DEFAULT_PASSWORD: "protectArda123"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge