# Generated by Django 4.0.6 on 2022-07-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humans_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HumanItems',
            new_name='HumanItem',
        ),
    ]
