# Generated by Django 4.0.6 on 2022-08-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elves_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElvenHumanWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
